# This is a basic workflow to help you get started with Actions

name: Upload

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag id'
        default: 'master'
        required: true
        type: string
  workflow_run:
    workflows: ["Build, release"]
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: extract version
        run : echo "PACKAGE_VERSION=$(node -p "require('./src-tauri/tauri.conf.json').package.version")" >> $GITHUB_ENV
        shell: bash
      - name: download
        env:
          PACKAGE_VERSION_2: ${{ env.PACKAGE_VERSION }}
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
        shell: bash
        run : |
          curl -u"$JFROG_USERNAME":"$JFROG_TOKEN" "https://arpitjaincalc.jfrog.io/artifactory/progress-generic-local/calc_"$PACKAGE_VERSION_2"_x64.exe" -o "calc_"$PACKAGE_VERSION_2"_x64.exe"
      - name: upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: calc_${{ env.PACKAGE_VERSION }}_x86.exe
