# This is a basic workflow to help you get started with Actions

name: Build, release, upload

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag id'
        default: 'alpha-0.0.01'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: extract version
        run : echo "PACKAGE_VERSION_TWO=$(node -p "require('./src-tauri/tauri.conf.json').package.version")" >> $GITHUB_ENV
        shell: bash
      - name: print version 1
        run : echo $PACKAGE_VERSION_TWO
        shell: bash
      - name: extract filename
        run : echo "FILE_NAME=./src-tauri/target/release/bundle/msi/calc_${PACKAGE_VERSION_TWO}_x64.dmg" >> $GITHUB_ENV
        shell: bash
      - name: print filename 1
        run : echo $FILE_NAME
        shell: bash
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: ${{ env.FILE_NAME }}
      - name: Test
        run: ls src-tauri/target/release/bundle/**/**
