# This is a basic workflow to help you get started with Actions

name: Build, release, upload

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag id'
        default: 'alpha-0.0.01'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.tag }}
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: get version
        run : echo "$(node -p "require('./src-tauri/tauri.conf.json')")"
        shell: bash
      - name: get version
        run : echo "$(node -p "require('./src-tauri/tauri.conf.json').package")"
        shell: bash

      - name: get version
        run : echo "$(node -p "require('./src-tauri/tauri.conf.json').package.version")"
        shell: bash
      - name: get version
        run : echo "PACKAGE_VERSION_TWO=$(node -p "require('./src-tauri/tauri.conf.json').package.version")" >> $GITHUB_ENV
        shell: bash

      - name: get version 1
        run : echo $PACKAGE_VERSION_TWO
        shell: bash
      - name: get version 2
        run : echo "$PACKAGE_VERSION_TWO"
        shell: bash
      - name: get version 3
        run : echo ${env:PACKAGE_VERSION_TWO}
        shell: bash

      - name: get version 4
        run : echo "${env:PACKAGE_VERSION_TWO}"
        shell: bash

      - name: get version 5
        run : echo "${{ env.PACKAGE_VERSION_TWO }}"
        
        
        shell: bash

      - name: get filename
        run : echo "FILE_NAME=./src-tauri/target/release/bundle/msi/calc_${{ env.PACKAGE_VERSION }}_x64.dmg" >> $GITHUB_ENV
        shell: bash

      - name : tes1
        run : echo "${{ env.FILE_NAME }}"
        shell: bash

      - name : tes1
        run : echo "${{ env.PACKAGE_VERSION }}"
        shell: bash

      - name: Test
        run: ls ${{ env.FILE_NAME }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "{{ env.FILE_NAME }}"
      - name: Test
        run: ls src-tauri/target/release/bundle/**/**
